/**
 * @qntx/nostr — public facade.
 *
 * Prefer layer subpaths for tree-shaking:
 * `@qntx/nostr/core`, `/signer`, `/relay`, `/client`, `/storage`, `/loaders`, `/gossip`, `/nips/*`
 *
 * Heavy NIPs are `@qntx/nostr/nips/<id>` only. There is no `@qntx/nostr/nips` barrel.
 */

// --- core (public) ---
export {
  EVENT_ID_BYTES,
  PUBLIC_KEY_BYTES,
  SECRET_KEY_BYTES,
  SIGNATURE_BYTES,
  SUBSCRIPTION_ID_MAX_CHARS,
  CryptoError,
  EventValidationError,
  HexError,
  MessageError,
  NostrError,
  UrlError,
  WasmVerifyPoisonedError,
  bytesToHex,
  hexToBytes,
  isHex32,
  isHex64,
  normalizeURL,
  utf8Decoder,
  utf8Encoder,
  Kind,
  classifyKind,
  isAddressableKind,
  isEphemeralKind,
  isRegularKind,
  isReplaceableKind,
  type KindClassification,
  type KindName,
  type KnownKind,
  Tag,
  eventAddress,
  formatEventAddress,
  getDTag,
  isTag,
  parseEventAddress,
  tagName,
  tagValue,
  type EventAddress,
  type TagInput,
  getEventHash,
  isMarkedVerified,
  isReplaceableWinner,
  itemCompare,
  serializeEvent,
  signedMatchesUnsigned,
  sortEvents,
  sortedEvents,
  validateEvent,
  validateSignedEvent,
  type Event,
  type EventTemplate,
  type UnsignedEvent,
  Keys,
  SecretKey,
  finalizeEvent,
  getPublicKey,
  publicKeyFromHex,
  signEvent,
  verifyEvent,
  type PublicKey,
  EventBuilder,
  type ProfileMetadata,
  canonicalizeFilter,
  canonicalizeFilters,
  cloneFilter,
  filterFingerprint,
  getFilterLimit,
  matchFilter,
  matchFilters,
  mergeFilters,
  type Filter,
  assertSubscriptionId,
  createSubscriptionId,
  encodeClientMessage,
  encodeRelayMessage,
  mergeCountHll,
  parseClientMessage,
  parseRelayMessage,
  type ClientMessage,
  type CountResult,
  type RelayMessage,
  type SubscriptionId,
} from "./core/index.ts";

// --- signer ---
export {
  KeysSigner,
  Nip07Signer,
  Nip46Signer,
  getWindowNostr,
  isNip07Available,
  type NostrSigner,
  type WindowNostr,
  type Nip46SignerOptions,
  type Nip46SubscribeOptions,
  type Nip46Transport,
} from "./signer/index.ts";

// --- curated NIPs (quick start) ---
export {
  Bech32MaxSize,
  decode as nip19Decode,
  decodeNostrURI,
  naddrEncode,
  neventEncode,
  noteEncode,
  nprofileEncode,
  npubEncode,
  nsecEncode,
  type AddressPointer,
  type DecodedResult,
  type EventPointer,
  type NAddr,
  type NEvent,
  type NProfile,
  type NPub,
  type NSec,
  type Note,
  type ProfilePointer,
  Nip19Error,
} from "./nips/nip19.ts";
export {
  buildReplyTags,
  parseThreadTags,
  replyTo,
  type ReplyTagsOptions,
  type ThreadReferences,
} from "./nips/nip10.ts";
export { makeAuthEvent, isAuthRequired } from "./nips/nip42.ts";
export {
  markerOf,
  parseRelayList,
  readRelays,
  relayListEventBuilder,
  relayListToTags,
  writeRelays,
  type RelayListItem,
  type RelayMarker,
} from "./nips/nip65.ts";

// --- relay ---
export {
  Pool,
  Relay,
  RelayClosedError,
  RelayConnectionError,
  RelayError,
  RelayPublishError,
  RelayStatus,
  isInsecureRelayUrl,
  useWebSocketImplementation,
  type PoolOptions,
  type PoolCountResult,
  type PoolPublishResult,
  type PublishResult,
  type RelayOptions,
  type RelayStatusName,
  type SubscribeOptions,
} from "./relay/index.ts";

// --- client / storage / loaders / gossip ---
export {
  Client,
  ClientBuilder,
  ClientError,
  type ClientOptions,
  type SendPrivateMessageOptions,
  type PrivateMessageSendResult,
  type ReceivedPrivateMessage,
  type FetchPrivateMessagesOptions,
  type SubscribePrivateMessagesOptions,
  SyncDirection,
  type SyncDirectionName,
  type SyncOptions,
  type SyncSummary,
} from "./client/index.ts";
export {
  MemoryEventStore,
  IndexedDbEventStore,
  StorageError,
  type EventStore,
  type PutResult,
  type NegentropyItem,
  type OutboxBound,
  type IndexedDbEventStoreOptions,
} from "./storage/index.ts";
export {
  createLoaders,
  createOutboxFeed,
  OutboxError,
  OutboxFeed,
  groupAuthorsByOutboxRelay,
  bareNostrUser,
  DataLoader,
  LoaderError,
  LoaderContext,
  ReplaceableCache,
  type Loaders,
  type ListResult,
  type NostrUser,
  type MutedEntity,
  type LoadStyle,
  type OutboxFeedOptions,
} from "./loaders/index.ts";
export { Gossip, type RoutedFilter, type PubkeyRoutes } from "./gossip/index.ts";
