/**
 * @qntx/nostr — public facade.
 *
 * Prefer layer subpaths for tree-shaking:
 * `@qntx/nostr/core`, `/signer`, `/relay`, `/client`, `/storage`, `/loaders`, `/gossip`, `/nips/*`
 */

// --- core (public) ---
export {
  EVENT_ID_BYTES,
  PUBLIC_KEY_BYTES,
  SECRET_KEY_BYTES,
  SIGNATURE_BYTES,
  SUBSCRIPTION_ID_MAX_CHARS,
  CryptoError,
  EventValidationError,
  HexError,
  MessageError,
  NostrError,
  UrlError,
  bytesToHex,
  hexToBytes,
  isHex32,
  isHex64,
  normalizeURL,
  utf8Decoder,
  utf8Encoder,
  Kind,
  classifyKind,
  isAddressableKind,
  isEphemeralKind,
  isRegularKind,
  isReplaceableKind,
  type KindClassification,
  type KindName,
  type KnownKind,
  Tag,
  eventAddress,
  formatEventAddress,
  getDTag,
  isTag,
  parseEventAddress,
  tagName,
  tagValue,
  type EventAddress,
  type TagTuple,
  type TagInput,
  getEventHash,
  isMarkedVerified,
  isReplaceableWinner,
  itemCompare,
  serializeEvent,
  signedMatchesUnsigned,
  sortEvents,
  sortedEvents,
  validateEvent,
  validateSignedEvent,
  type Event,
  type EventTemplate,
  type UnsignedEvent,
  Keys,
  SecretKey,
  finalizeEvent,
  getPublicKey,
  publicKeyFromHex,
  signEvent,
  verifyEvent,
  type PublicKey,
  EventBuilder,
  type ProfileMetadata,
  cloneFilter,
  filterFingerprint,
  getFilterLimit,
  matchFilter,
  matchFilters,
  mergeFilters,
  type Filter,
  createSubscriptionId,
  encodeClientMessage,
  encodeRelayMessage,
  mergeCountHll,
  parseClientMessage,
  parseRelayMessage,
  type ClientMessage,
  type CountResult,
  type RelayMessage,
  type SubscriptionId,
} from "./core/index.ts";

// --- signer ---
export {
  KeysSigner,
  Nip07Signer,
  Nip46Signer,
  getWindowNostr,
  isNip07Available,
  type NostrSigner,
  type WindowNostr,
  type Nip46SignerOptions,
  type Nip46SubscribeOptions,
  type Nip46Transport,
} from "./signer/index.ts";

// --- nips ---
export {
  Bech32MaxSize,
  decode as nip19Decode,
  decodeNostrURI,
  naddrEncode,
  neventEncode,
  noteEncode,
  nprofileEncode,
  npubEncode,
  nsecEncode,
  type AddressPointer,
  type DecodedResult,
  type EventPointer,
  type NAddr,
  type NEvent,
  type NProfile,
  type NPub,
  type NSec,
  type Note,
  type ProfilePointer,
  Nip19Error,
} from "./nips/nip19.ts";
export {
  buildReplyTags,
  eTag,
  parseThreadTags,
  replyTo,
  type ReplyTagsOptions,
  type ThreadReferences,
} from "./nips/nip10.ts";
export { Nip13Error, getPow, minePow, type MinePowOptions } from "./nips/nip13.ts";
export { isNostrURI, NOSTR_URI_REGEX, parseNostrURI, type NostrURI } from "./nips/nip21.ts";
export { parseContent, parseContentBlocks, type ContentBlock } from "./nips/nip27.ts";
export { encrypt as nip04Encrypt, decrypt as nip04Decrypt } from "./nips/nip04.ts";
export {
  NIP05_REGEX,
  NIP05_ROOT_LOCAL,
  WELL_KNOWN_PATH,
  Nip05Error,
  isNip05,
  lookupFromDocument,
  parseNip05,
  parseNip05Document,
  queryProfile,
  verifyNip05,
  wellKnownUrl,
  type Nip05,
  type Nip05Address,
  type Nip05Document,
  type Nip05Fetch,
  type Nip05Nip46,
} from "./nips/nip05.ts";
export {
  Nip11Error,
  fetchRelayInformation,
  relayInfoHttpUrl,
  type Nip11Fetch,
  type RelayInformation,
} from "./nips/nip11.ts";
export { makeAuthEvent, isAuthRequired } from "./nips/nip42.ts";
export {
  calcPaddedLen,
  decrypt as nip44Decrypt,
  decryptFromPubkey,
  encrypt as nip44Encrypt,
  encryptToPubkey,
  getConversationKey,
} from "./nips/nip44.ts";
export {
  markerOf,
  parseRelayList,
  readRelays,
  relayListEventBuilder,
  relayListToTags,
  writeRelays,
  type RelayListItem,
  type RelayMarker,
} from "./nips/nip65.ts";
export {
  bookmarkListEventBuilder,
  decryptPrivateTags,
  encryptPrivateTags,
  muteListEventBuilder,
  parseBookmarkList,
  parseEmojiSet,
  parseFavoriteRelays,
  parseFollowPack,
  parseMuteList,
  parseMuteListPrivate,
  parsePinList,
  parseRelaySet,
  parseUserEmojiList,
  pinListEventBuilder,
  type MuteItem,
  type Nip51Crypto,
} from "./nips/nip51.ts";
export {
  Nip59Error,
  TWO_DAYS_SECS,
  createRumor,
  createSeal,
  createGiftWrap,
  wrap as wrapGift,
  unwrap as unwrapGift,
  randomPastTimestamp,
  rumorToJson,
  eventToJson,
  isGiftWrapKind,
  requireNip59Crypto,
  requireNip44Decryptor,
  type Rumor,
  type Nip59Crypto,
  type Nip44Decryptor,
  type GiftWrapTimestamps,
  type WrapOptions,
  type SealOptions,
  type TimestampRandomize,
} from "./nips/nip59.ts";
export {
  dmRelayListEventBuilder,
  dmRelayListToTags,
  parseDmRelayList,
  Nip17Error,
  normalizeRecipients,
  buildChatMessageRumor,
  wrapDirectMessage,
  requireDmRelays,
  type Recipient,
  type ReplyTo,
  type ChatMessageOptions,
} from "./nips/nip17.ts";
export {
  BUNKER_REGEX,
  Nip46Error,
  createNostrConnectURI,
  decodeNip46Request,
  decodeNip46Response,
  encodeNip46Request,
  encodeNip46Response,
  parseBunkerURL,
  parseNostrConnectURI,
  toBunkerURL,
  type BunkerPointer,
  type ClientMetadata,
  type Nip46Request,
  type Nip46Response,
  type NostrConnectParams,
} from "./nips/nip46.ts";
export {
  makeZapRequest,
  parseBolt11,
  parseZapRequestFromReceipt,
  validateZapReceipt,
  type Bolt11Fields,
  type EventZapRequest,
  type ProfileZapRequest,
  type ZapReceiptContext,
  type ZapReceiptValidation,
} from "./nips/nip57.ts";
export {
  encrypt as nip49Encrypt,
  decrypt as nip49Decrypt,
  Nip49Error,
  type KeySecurityByte,
  type Ncryptsec,
} from "./nips/nip49.ts";
export {
  Nip77Error,
  PROTOCOL_VERSION,
  DEFAULT_FRAME_SIZE_LIMIT,
  MAX_NEG_ROUNDS,
  NegentropyStorageVector,
  Negentropy,
  Reconciliation,
  Responder,
  storageFromEvents,
  storageFromItems,
  type NegItem,
  type ReconcileOutcome,
} from "./nips/nip77.ts";
export {
  Nip96Error,
  fetchNip96Info,
  parseNip96UploadResponse,
  uploadNip96,
  type Nip96Fetch,
  type Nip96ServerInfo,
  type Nip96UploadResult,
} from "./nips/nip96.ts";
export {
  Nip98Error,
  getToken as nip98GetToken,
  unpackEventFromToken,
  validateAuthEvent,
} from "./nips/nip98.ts";
export {
  BlossomError,
  blobExists,
  blossomServerListEventBuilder,
  checkUpload,
  createAuthTemplate,
  createUploadAuth,
  deleteBlob,
  encodeAuthorizationHeader,
  getBlob,
  getHashFromURL,
  healBlobUrl,
  listBlobs,
  mirrorBlob,
  parseBlossomServerList,
  sha256Blob,
  upload,
  uploadToServers,
  verifyBlob,
  type BlobDescriptor,
  type BlossomAuthVerb,
  type BlossomFetch,
  type BlossomSign,
} from "./nips/blossom.ts";

// --- relay ---
export {
  Pool,
  Relay,
  RelayClosedError,
  RelayConnectionError,
  RelayError,
  RelayPublishError,
  RelayStatus,
  isInsecureRelayUrl,
  useWebSocketImplementation,
  type PoolOptions,
  type PoolCountResult,
  type PoolPublishResult,
  type PublishResult,
  type RelayOptions,
  type RelayStatusName,
  type SubscribeOptions,
} from "./relay/index.ts";

// --- client / storage / loaders / gossip ---
export {
  Client,
  ClientBuilder,
  type ClientOptions,
  type SendPrivateMessageOptions,
  type PrivateMessageSendResult,
  type ReceivedPrivateMessage,
  type FetchPrivateMessagesOptions,
  type SubscribePrivateMessagesOptions,
  SyncDirection,
  type SyncDirectionName,
  type SyncOptions,
  type SyncSummary,
} from "./client/index.ts";
export {
  MemoryEventStore,
  IndexedDbEventStore,
  StorageError,
  type EventStore,
  type PutResult,
  type NegentropyItem,
  type OutboxBound,
  type IndexedDbEventStoreOptions,
} from "./storage/index.ts";
export {
  createLoaders,
  createOutboxFeed,
  OutboxError,
  OutboxFeed,
  groupAuthorsByOutboxRelay,
  bareNostrUser,
  DataLoader,
  LoaderError,
  LoaderContext,
  ReplaceableCache,
  type Loaders,
  type ListResult,
  type NostrUser,
  type MutedEntity,
  type LoadStyle,
  type OutboxFeedOptions,
} from "./loaders/index.ts";
export { Gossip, type BrokenDownFilters, type PubkeyRoutes } from "./gossip/index.ts";
